# Generated by Django 6.0.5 on 2026-05-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicologos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='psicologo',
            table='psicologo',
        ),
    ]
