# Generated by Django 6.0.5 on 2026-05-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primeira_senha',
            field=models.BooleanField(default=False),
        ),
    ]
