# Generated by Django 6.0.5 on 2026-05-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_primeira_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='avatar',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='perfil_configurado',
            field=models.BooleanField(default=False),
        ),
    ]
