# Generated by Django 6.0.5 on 2026-05-22 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_paciente_avatar_paciente_perfil_configurado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatos', to='app.paciente')),
            ],
            options={
                'db_table': 'relatos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
