# Generated by Django 6.0.5 on 2026-05-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_relato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='avatar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
