# Generated by Django 6.0.5 on 2026-05-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_paciente_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='relato',
            name='humor',
            field=models.CharField(choices=[('muito_feliz', 'Muito Feliz'), ('feliz', 'Feliz'), ('neutro', 'Neutro'), ('triste', 'Triste'), ('muito_triste', 'Muito Triste')], default='neutro', max_length=20),
        ),
    ]
